---
# This Playbook deploys gitlab!

- hosts: gitlab
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: root
  roles:
    - git-ppa/roles/ppa-dep
    - git-ppa
  tasks:
  - include: tasks/install-dependencies.yml

  - include: tasks/handle-updates.yml
  - include: tasks/update/update-5-4-stable-to-6-0-pre.yml
    when: previous_gitlab_version == "5-4-stable" and gitlab_version == "master"

  - include: tasks/install-gitlab-shell.yml

  - include: tasks/install-mysql.yml
    when: database == 'mysql'

  - include: tasks/install-gitlab.yml
  - include: tasks/install-gems.yml
  - include: tasks/initialize-database.yml
  - include: tasks/install-init-script.yml

  - include: tasks/install-nginx.yml
    when: webserver == 'nginx'

  - include: tasks/set-installed-version.yml

  handlers:
   - include: handlers/main.yml
