---
# This Playbook deploys gitlab!

- hosts: gitlab
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles:
    - git-ppa/roles/ppa-dep
    - git-ppa
    - gitlab-ruby-deps
    - ruby-from-src 
    - {role: ssl-certs, when: https == 'true'}
  tasks:
  - include: tasks/install-dependencies.yml
  - include: tasks/install-gitlab-shell.yml

  - include: tasks/install-mysql.yml
    when: database == 'mysql'

  - include: tasks/install-gitlab.yml
  - include: tasks/install-gems.yml
  - include: tasks/initialize-database.yml
  - include: tasks/install-init-script.yml

  - include: tasks/install-nginx.yml
    when: webserver == 'nginx'

  handlers:
   - include: handlers/main.yml
