---
# Gitlab playbook

- name: install mysql dependencies
  action: apt pkg=$item state=installed
  with_items:
    - mysql-server 
    - mysql-client 
    - libmysqlclient-dev
    - python-mysqldb

- name: ensure database user gitlab is present
  mysql_user: state=present name=$gitlabDatabaseUsername host=localhost password=$gitlabDatabasePassword

- name: ensure database gitlabhq_production is present
  mysql_db: state=present name=gitlabhq_production collation=utf8_unicode_ci encoding=utf8

- name: ensure database user gitlab has necessary privleges
  mysql_user: state=present name=gitlab priv=$gitlab_mysql_priv
