---
# Gitlab dependencies playbook

# Make sure right version of python will be used
- name: ensure /usr/local/bin/python2 links to /usr/bin/python
  file: state=link src=/usr/bin/python path=/usr/local/bin/python2

# Install bundler
- name: ensure bundler is installed
  gem: name=bundler state=present 

# Add git user
- name: ensure user git is present
  user: state=present name=git system=yes shell=/bin/sh comment="Git Version Control" 
