---
# Installs gitlab shell

# Clone gitlab shell
- name: gitlab | Get gitlab-shell source
  git: repo=https://github.com/gitlabhq/gitlab-shell.git dest=$gitlab_base_dir/gitlab-shell version=$gitlabShellVersion
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | Set git as owner
  file: path=$gitlab_base_dir/gitlab-shell owner=git group=git recurse=yes state=directory

- name: gitlab | Set the /home/git/gitlab-shell/config.yml
  template: src=templates/home/git/gitlab-shell/config.yml.j2 dest=$gitlab_base_dir/gitlab-shell/config.yml owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

# Do setup
- name: gitlab | Install gitlab-shell
  command: sudo -u $gitlab_git_user -H ./bin/install chdir=$gitlab_base_dir/gitlab-shell creates=$gitlab_base_dir/repositories

#Install also touches this file, multiple creates=?
## File used as authorized_keys for gitlab user
#auth_file: "/home/git/.ssh/authorized_keys"
