- name: ensure init script is installed
  copy: src=files/etc/init.d/gitlab dest=/etc/init.d/gitlab owner=root group=root mode=0755

- name: make GitLab start on boot 
  command: update-rc.d gitlab defaults 21

- name: restart GitLab
  service: name=gitlab state=started
