---

# Play book installs gitlab
- name: gitlab | clone gitlab source
  git: repo=https://github.com/gitlabhq/gitlabhq.git dest=$gitlab_base_dir/gitlab version=$gitlabVersion
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | gitlab should be owned by git user
  file: path=$gitlab_base_dir/gitlab owner=git group=git recurse=yes state=directory

- name: gitlab | Set the gitlab.yml configuration file
  template: src=home/git/gitlab/config/gitlab.yml.j2 dest=$gitlab_base_dir/gitlab/config/gitlab.yml owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure copy of unicorn config exists 
  template: src=home/git/gitlab/config/unicorn.rb.j2 dest=$gitlab_base_dir/gitlab/config/unicorn.rb owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure copy of database config exists 
  template: src=home/git/gitlab/config/database.yml.j2 dest=$gitlab_base_dir/gitlab/config/database.yml owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to log (1)
  file: state=directory path=$gitlab_base_dir/gitlab/log owner=git recurse=yes
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to log (2)
  command: chmod -R u+rwX $gitlab_base_dir/gitlab/log
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to tmp (1)
  file: state=directory path=$gitlab_base_dir/gitlab/tmp owner=git recurse=yes
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to tmp (2)
  command: chmod -R u+rwX $gitlab_base_dir/gitlab/tmp
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure directory for satellites exists
  file: state=directory path=$gitlab_base_dir/gitlab-satellites owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | Create directory for pids and make sure GitLab can write to it
  file: path=$gitlab_base_dir/gitlab/tmp/pids/ state=directory owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to pid
  command: chmod -R u+rwX $gitlab_base_dir/gitlab/tmp/pids
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | Create directory for sockets and make sure GitLab can write to it
  file: path=$gitlab_base_dir/gitlab/tmp/sockets/ state=directory owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to sockets
  command: chmod -R u+rwX $gitlab_base_dir/gitlab/tmp/sockets
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | Create directory for uploads and make sure GitLab can write to it
  file: path=$gitlab_base_dir/gitlab/public/uploads/ state=directory owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure GitLab can write to uploads 
  command: chmod -R u+rwX $gitlab_base_dir/gitlab/public/uploads
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure copy of puma config exists
  template: src=home/git/gitlab/config/puma.rb.j2 dest=$gitlab_base_dir/gitlab/config/puma.rb owner=git group=git

- name: gitlab | Set git global user name
  command: sudo -u git -H git config --global user.name "$gitGlobalUserName" chdir=$gitlab_base_dir/gitlab
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | Set git global user email
  command: sudo -u git -H git config --global user.email "$gitGlobalUserEmail" chdir=$gitlab_base_dir/gitlab
  sudo: yes
  sudo_user: $gitlab_git_user

- name: gitlab | ensure copy of ssh config exists
  template: src=home/git/.ssh/config.j2 dest=/home/$gitlab_git_user/.ssh/config owner=git group=git
  sudo: yes
  sudo_user: $gitlab_git_user
