- name: ensure package nginx is present
  apt: pkg=nginx state=installed

- name: set the gitlab nginx config
  template: src=templates/etc/nginx/sites-available/gitlab.j2 dest=/etc/nginx/sites-available/gitlab mode=0755

- name: ensure default Nginx site is not enabled
  file: state=absent path=/etc/nginx/sites-enabled/default

- name: ensure GitLab Nginx site is enabled
  file: state=link src=/etc/nginx/sites-available/gitlab path=/etc/nginx/sites-enabled/gitlab

- name: restart nginx 
  service: name=nginx state=started

