---
# Gitlab playbook

- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: install gitlab dependencies 
  action: apt pkg=$item state=installed
  with_items:
    - build-essential 
    - zlib1g-dev 
    - libyaml-dev 
    - libssl-dev 
    - libgdbm-dev 
    - libreadline-dev 
    - libncurses5-dev 
    - libffi-dev 
    - curl 
    - openssh-server 
    - redis-server 
    - checkinstall 
    - libxml2-dev 
    - libxslt1-dev # The installation document says libxslt-dev, but I guess this is okay
    - libcurl4-openssl-dev 
    - libicu-dev
    - python
    #- postfix 

# Make sure right version of python will be used
- name: ensure /usr/local/bin/python2 links to /usr/bin/python
  file: state=link src=/usr/bin/python path=/usr/local/bin/python2

# Install correct version of ruby from source
- name: ensure directory /tmp/ruby is present
  file: state=directory path=/tmp/ruby

- name: ensure ruby is downloaded
  get_url: url=$rubyUrl dest=/tmp/ruby

- name: ensure ruby is extracted
  command: tar -xf ruby-1.9.3-p392.tar.gz chdir=/tmp/ruby creates=$tmpRubyPath

- name: ensure ruby is configured
  command: ./configure chdir=$tmpRubyPath creates=$tmpRubyPath/Makefile

- name: ensure ruby is compiled
  command: make chdir=$tmpRubyPath creates=$tmpRubyPath/ruby

- name: ensure ruby is installed
  command: make install chdir=$tmpRubyPath creates=/usr/local/bin/ruby

# Install bundler
- name: ensure bundler is installed
  gem: name=bundler state=present 
# command: gem install bundler creates=/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.3.0

# Add git user
- name: ensure user git is present
  # Possible problem is that --disabled-password is not set explicitly – I couldn’t find anything like that.
  user: state=present name=git system=yes shell=/bin/sh comment="Git Version Control" 
